log-level: debug

udp: :55
# doh: :443
# cert: conf/cert.pem
# key: conf/key.pem
geosite: conf/geosite.dat

bootstrap-dns:
  - 223.5.5.5
  - 223.6.6.6

cache:
  max-counters: 10000
  max-cost: 10000
  buffer-items: 64
  ttl: 24h

upstream:
  alidns: 223.5.5.5
  googledns: dns.google
  mydns: 8.8.8.8

default-upstream: mydns

route:
  - mydns(suffix("my.dev", "myssh.com"))
  - alidns(geosite("aliyun", "alibaba"), suffix("aliyun.com"))
  - mydns(geosite("github", "google", "openai", "anthropic"))
  - alidns(geosite("cn"))