log-level: debug

udp: :55
doh: :443
cert: conf/cert.pem
key: conf/key.pem
geosite: conf/geosite.dat
# 是否阻止 AAAA 查询（IPv6）
block-aaaa: true

bootstrap-dns:
  - 223.5.5.5
  - 223.6.6.6

cache:
  max-counters: 10000
  max-cost: 10000
  buffer-items: 64
  ttl: 24h
  # 覆盖最小 TTL 值, 单位为秒
  # 如果设置为 0，则不覆盖最小 TTL 值
  min-ttl: 60 # 1 分钟
  # 覆盖最大 TTL 值, 单位为秒
  # 如果设置为 0，则不覆盖最大 TTL 值
  max-ttl: 86400 # 1 天

upstream:
  alidns: 223.5.5.5
  googledns: dns.google
  mydns: 8.8.8.8

default-upstream: mydns

route:
  - mydns(suffix("my.dev", "myssh.com"))
  - alidns(geosite("aliyun", "alibaba"), suffix("aliyun.com"))
  - mydns(geosite("github", "google", "openai", "anthropic"))
  - alidns(geosite("cn"))

rewrite:
  - domain: test.example.com
    type: A
    value: 127.0.0.1
    response-type: normal
