# 日志级别（debug/info/warn/error）
log-level: debug
# # UDP 服务监听地址（默认端口 53）
# udp: :53
# # TCP 服务监听地址（可选）
# tcp: :53
# # 是否禁用 AAAA 记录（IPv6）
# block-aaaa: true
# HTTPS 证书路径（可选，启用 TLS）
#cert: conf/cert.pem
# HTTPS 私钥路径（可选）
#key: conf/key.pem
# 自定义 GeoSite 路径（可选）
geosite: geosite.dat

# DoH 服务监听地址
#doh: :443

# # STCP 配置
# stcp:
#   # STCP 服务监听地址
#   addr: :553
#   # 通信密码（需与客户端一致）
#   password: 123456

inbound:
  tcp: { type: 'tcp', addr: ':553' }

# Bootstrap DNS 服务器
bootstrap-dns:
  - 223.5.5.5
  - 223.6.6.6

# 缓存配置
cache:
  # 最大缓存条目数
  max-counters: 10000
  # 最大缓存成本（与条目大小相关）
  max-cost: 10000
  # 写缓存数量
  buffer-items: 64
  # 缓存默认 TTL
  ttl: 24h
  # 最小覆盖 TTL (format: 1h, 1m, 1s)
  min-ttl: 60s
  # 最大覆盖 TTL
  max-ttl: 24h

# 上游配置
upstream:
  # UDP 上游（自动补全为 udp://223.5.5.5:53）
  alidns: 223.5.5.5
  # 支持域名（自动通过 bootstrap DNS 解析）
  googledns: dns.google
  # STCP 上游（密码:123456）
  mydns: stcp://123456@127.0.0.1:553
# 默认上游（未配置时使用第一个）
default-upstream: mydns

# 上游配置
outbound:
  # UDP 上游（自动补全为 udp://223.5.5.5:53）
  alidns: tls://223.5.5.5:853
  mydns: stcp://123456@127.0.0.1:5053

  # 路由配置
route:
  block-aaaa: true
  rules:
    # 国内域名使用 alidns
    - alidns(geosite("cn"))
  default: mydns

# 重写配置
rewrite:
  min-ttl: 600s
  max-ttl: 24h
  rule:
      # 目标域名
    - domain: test.example.com
      # 记录类型（A/AAAA/CNAME/TXT）
      type: A
      # 重写值（IP/CNAME/TXT内容）
      value: 127.0.0.1
      # 自定义 TTL
      ttl: 60s
