# 日志级别（debug/info/warn/error）
log-level: debug
# 自定义 GeoSite 路径（可选）
geosite: geosite.dat

# 入站配置
inbound:
  udp: { type: 'udp', addr: ':55' }
  tcp: { type: 'tcp', addr: ':55' }
  tls: { type: 'tls', addr: ':853', cert: 'conf/cert.pem', key: 'conf/key.pem' }
  stcp: { type: 'stcp', addr: ':553', password: '123456' }
  http: { type: 'http', addr: ':80' }
  https: { type: 'https', addr: ':443', cert: 'conf/cert.pem', key: 'conf/key.pem' }

# Bootstrap DNS 服务器
bootstrap-dns:
  - 223.5.5.5
  - 223.6.6.6

# 缓存配置
cache:
  # 最大缓存条目数
  max-counters: 10000
  # 最大缓存成本（与条目大小相关）
  max-cost: 10000
  # 写缓存数量
  buffer-items: 64
  # 缓存默认 TTL
  ttl: 24h
  # 最小覆盖 TTL (format: 1h, 1m, 1s)
  min-ttl: 20s
  # 最大覆盖 TTL
  max-ttl: 24h
  # 缓存线程数
  threads: 5
  # 重新请求 TTL
  refresh-ttl: 5m

# 出站配置
outbound:
  # UDP 上游（自动补全为 udp://223.5.5.5:53）
  udpdns: udp://223.5.5.5:53
  tcpdns: tcp://223.5.5.5:53
  tlsdns: tls://223.5.5.5:853
  stcpdns: stcp://123456@223.5.5.5:553
  httpsdns: https://dns.alidns.com/dns-query

# 路由配置
route:
  block-aaaa: true
  rules:
    # 国内域名使用 alidns
    - httpsdns(geosite("cn"))
  default: httpsdns

# 重写配置
rewrite:
  min-ttl: 10s
  max-ttl: 24h
  rule:
      # 目标域名
    - domain: test.example.com
      # 记录类型（A/AAAA/CNAME/TXT）
      type: A
      # 重写值（IP/CNAME/TXT内容）
      value: 127.0.0.1
      # 自定义 TTL
      ttl: 5s
