name: Docker

on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # 关键：允许推送到 ghcr.io

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set develop
        if: github.ref == 'refs/heads/main'
        run: |
          TAGS="ghcr.io/${{ github.repository }}:develop,${{ github.repository }}:develop"
          echo "TAGS=${TAGS}" >> "${GITHUB_ENV}"
      - name: Set develop
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAGS="ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME},${{ github.repository }}:${GITHUB_REF_NAME}"
          TAGS="${TAGS},ghcr.io/${{ github.repository }}:latest,${{ github.repository }}:latest"
          echo "TAGS=${TAGS}" >> "${GITHUB_ENV}"

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.TAGS }}
