name: Build and Push Docker Image

on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # 关键：允许推送到 ghcr.io

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tags
        run: |
          if [[ "${GITHUB_REF}" == "refs/tags/"* ]]; then
            TAGS="ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME},${{ github.repository }}:${GITHUB_REF_NAME}"
            TAGS="ghcr.io/${{ github.repository }}:latest,${{ github.repository }}:latest"
          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            TAGS="ghcr.io/${{ github.repository }}:develop,${{ github.repository }}:develop"
          else
            echo "Unsupported ref: ${GITHUB_REF}"
            exit 1
          fi
          echo "TAGS=${TAGS}" >> "${GITHUB_ENV}"

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.TAGS }}
