name: Build and Push Docker Image

on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # 关键：允许推送到 ghcr.io

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set tag
        run: |
          if [[ "${GITHUB_REF}" == "refs/tags/"* ]]; then
            TAG_NAME="${GITHUB_REF_NAME}"
          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            TAG_NAME="develop"
          else
            echo "Unsupported ref: ${GITHUB_REF}"
            exit 1
          fi
          echo "TAG_NAME=${TAG_NAME}" >> "${GITHUB_ENV}"

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags:
            # 始终推送动态标签 (tag触发时是具体版本号, main分支时是develop)
            - ghcr.io/${{ github.repository }}:${{ env.TAG_NAME }}
            - ${{ github.repository }}:${{ env.TAG_NAME }}
            # 仅当触发类型为tag时额外推送latest标签
            - ${{ github.ref_type == 'tag' && format('ghcr.io/{0}:latest', github.repository) || '' }}
            - ${{ github.ref_type == 'tag' && format('{0}:latest', github.repository) || '' }}
